/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateFixedDepositsRouteImport } from './routes/corporate-fixed-deposits'
import { Route as GiftCityRouteImport } from './routes/gift-city'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as LoanAgainstSecuritiesRouteImport } from './routes/loan-against-securities'
import { Route as MutualFundsRouteImport } from './routes/mutual-funds'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SifRouteImport } from './routes/sif'
import { Route as TaxSavingBondsRouteImport } from './routes/tax-saving-bonds'
import { Route as UnlistedSharesRouteImport } from './routes/unlisted-shares'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateFixedDepositsRoute = CorporateFixedDepositsRouteImport.update({
  id: '/corporate-fixed-deposits',
  path: '/corporate-fixed-deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCityRoute = GiftCityRouteImport.update({
  id: '/gift-city',
  path: '/gift-city',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanAgainstSecuritiesRoute = LoanAgainstSecuritiesRouteImport.update({
  id: '/loan-against-securities',
  path: '/loan-against-securities',
  getParentRoute: () => rootRouteImport,
} as any)
const MutualFundsRoute = MutualFundsRouteImport.update({
  id: '/mutual-funds',
  path: '/mutual-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SifRoute = SifRouteImport.update({
  id: '/sif',
  path: '/sif',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxSavingBondsRoute = TaxSavingBondsRouteImport.update({
  id: '/tax-saving-bonds',
  path: '/tax-saving-bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlistedSharesRoute = UnlistedSharesRouteImport.update({
  id: '/unlisted-shares',
  path: '/unlisted-shares',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-fixed-deposits': typeof CorporateFixedDepositsRoute
  '/gift-city': typeof GiftCityRoute
  '/insurance': typeof InsuranceRoute
  '/loan-against-securities': typeof LoanAgainstSecuritiesRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/services': typeof ServicesRoute
  '/sif': typeof SifRoute
  '/tax-saving-bonds': typeof TaxSavingBondsRoute
  '/unlisted-shares': typeof UnlistedSharesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-fixed-deposits': typeof CorporateFixedDepositsRoute
  '/gift-city': typeof GiftCityRoute
  '/insurance': typeof InsuranceRoute
  '/loan-against-securities': typeof LoanAgainstSecuritiesRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/services': typeof ServicesRoute
  '/sif': typeof SifRoute
  '/tax-saving-bonds': typeof TaxSavingBondsRoute
  '/unlisted-shares': typeof UnlistedSharesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate-fixed-deposits': typeof CorporateFixedDepositsRoute
  '/gift-city': typeof GiftCityRoute
  '/insurance': typeof InsuranceRoute
  '/loan-against-securities': typeof LoanAgainstSecuritiesRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/services': typeof ServicesRoute
  '/sif': typeof SifRoute
  '/tax-saving-bonds': typeof TaxSavingBondsRoute
  '/unlisted-shares': typeof UnlistedSharesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-fixed-deposits'
    | '/gift-city'
    | '/insurance'
    | '/loan-against-securities'
    | '/mutual-funds'
    | '/services'
    | '/sif'
    | '/tax-saving-bonds'
    | '/unlisted-shares'
    | '/why-choose-us'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-fixed-deposits'
    | '/gift-city'
    | '/insurance'
    | '/loan-against-securities'
    | '/mutual-funds'
    | '/services'
    | '/sif'
    | '/tax-saving-bonds'
    | '/unlisted-shares'
    | '/why-choose-us'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/corporate-fixed-deposits'
    | '/gift-city'
    | '/insurance'
    | '/loan-against-securities'
    | '/mutual-funds'
    | '/services'
    | '/sif'
    | '/tax-saving-bonds'
    | '/unlisted-shares'
    | '/why-choose-us'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CorporateFixedDepositsRoute: typeof CorporateFixedDepositsRoute
  GiftCityRoute: typeof GiftCityRoute
  InsuranceRoute: typeof InsuranceRoute
  LoanAgainstSecuritiesRoute: typeof LoanAgainstSecuritiesRoute
  MutualFundsRoute: typeof MutualFundsRoute
  ServicesRoute: typeof ServicesRoute
  SifRoute: typeof SifRoute
  TaxSavingBondsRoute: typeof TaxSavingBondsRoute
  UnlistedSharesRoute: typeof UnlistedSharesRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-fixed-deposits': {
      id: '/corporate-fixed-deposits'
      path: '/corporate-fixed-deposits'
      fullPath: '/corporate-fixed-deposits'
      preLoaderRoute: typeof CorporateFixedDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-city': {
      id: '/gift-city'
      path: '/gift-city'
      fullPath: '/gift-city'
      preLoaderRoute: typeof GiftCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-against-securities': {
      id: '/loan-against-securities'
      path: '/loan-against-securities'
      fullPath: '/loan-against-securities'
      preLoaderRoute: typeof LoanAgainstSecuritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutual-funds': {
      id: '/mutual-funds'
      path: '/mutual-funds'
      fullPath: '/mutual-funds'
      preLoaderRoute: typeof MutualFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sif': {
      id: '/sif'
      path: '/sif'
      fullPath: '/sif'
      preLoaderRoute: typeof SifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-saving-bonds': {
      id: '/tax-saving-bonds'
      path: '/tax-saving-bonds'
      fullPath: '/tax-saving-bonds'
      preLoaderRoute: typeof TaxSavingBondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlisted-shares': {
      id: '/unlisted-shares'
      path: '/unlisted-shares'
      fullPath: '/unlisted-shares'
      preLoaderRoute: typeof UnlistedSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CorporateFixedDepositsRoute: CorporateFixedDepositsRoute,
  GiftCityRoute: GiftCityRoute,
  InsuranceRoute: InsuranceRoute,
  LoanAgainstSecuritiesRoute: LoanAgainstSecuritiesRoute,
  MutualFundsRoute: MutualFundsRoute,
  ServicesRoute: ServicesRoute,
  SifRoute: SifRoute,
  TaxSavingBondsRoute: TaxSavingBondsRoute,
  UnlistedSharesRoute: UnlistedSharesRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
